# FAISS Tutorial

This notebook demonstrates the functionality of the FAISS library

In [6]:
import os
import numpy as np
from file_processing import faiss_index

In [3]:
# load sample embeddings and query vectors
embeddings = np.load("tests/resources/faiss_test_files/sample_embeddings.npy")
query_vec = np.load("tests/resources/faiss_test_files/sample_query_vector.npy")

**Create an index and run a query**

The output of the query will be a tuple representing the distance between the query vector and the documents along with the indexes of the documents in the faiss index

In [5]:
# create a faiss index
flat_index = faiss_index.create_flat_index(embeddings)
# query the index
flat_index.query(query_vec, k=1)

(array([[37.001266],
        [26.461792]], dtype=float32),
 array([[14],
        [15]], dtype=int64))

**Save the index**

The index can be saved by calling the save function or by specifying a file path upon creating the index

In [7]:
# save the index
flat_index.save_index("tests/resources/faiss_test_files/flat_index.faiss")

In [8]:
# save when creating the index
flat_index = faiss_index.create_flat_index(embeddings, "tests/resources/faiss_test_files/flat_index.faiss")

In [9]:
# clean up files
os.remove("tests/resources/faiss_test_files/flat_index.faiss")

**Load an index from a file**

A previously created FAISS index can be loaded from a file

In [10]:
index_from_file = faiss_index.load_index("tests/resources/faiss_test_files/flat.faiss")
index_from_file.query(query_vec)

(array([[37.001266],
        [26.461792]], dtype=float32),
 array([[14],
        [15]], dtype=int64))